services:
  users:
    build:
      context: .
      dockerfile: Dockerfile.qa
    restart: always
    container_name: users_subgraph_qa
    image: users_subgraph_qa
    ports:
      - "4101:4001"
    env_file:
      - .env.qa
    environment:
      - NODE_ENV=qa
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
