services:
  users:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    container_name: users_subgraph_prod
    image: users_subgraph_prod
    ports:
      - "4001:4001"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
