version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - chilean
  - ekoru
  - KHIPU
  - TIKTOK
  - UPCYCLING
  - WEBPAY
ignoreWords:
  - datasource
  - postgresql
  - uuid
import: []
