services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: user-service
    ports:
      - "9001:9001"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
