services:
  admin-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: admin-api
    ports:
      - "4500:4500"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
